# Generated by Django 5.2.1 on 2025-05-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('rating', models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Nominal'), (4, 'High'), (5, 'Very High'), (6, 'Extra High')])),
                ('category', models.CharField(choices=[('PRODUCT', 'Product'), ('COMPUTER', 'Computer'), ('PERSONNEL', 'Personnel'), ('PROJECT', 'Project')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
