# Generated by Django 5.2.1 on 2025-05-22 19:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Nominal'), (4, 'High'), (5, 'Very High'), (6, 'Extra High')])),
                ('category', models.CharField(choices=[('PRODUCT', 'Product'), ('COMPUTER', 'Computer'), ('PERSONNEL', 'Personnel'), ('PROJECT', 'Project')], max_length=50)),
                ('effort_multiplier', models.FloatField(help_text='Effort multiplier for this cost driver', validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('model_family', models.CharField(choices=[('COCOMO_81', 'COCOMO 81'), ('COCOMO_II', 'COCOMO II')], max_length=20)),
                ('size_kloc', models.FloatField(help_text='Size in thousands of lines of code (KLOC)', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScaleDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Nominal'), (4, 'High'), (5, 'Very High'), (6, 'Extra High')])),
                ('weight', models.FloatField(help_text='Weight factor for the scale driver (0.0 to 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCostDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Nominal'), (4, 'High'), (5, 'Very High'), (6, 'Extra High')])),
                ('cost_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.costdriver')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project')),
            ],
            options={
                'unique_together': {('project', 'cost_driver')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='cost_drivers',
            field=models.ManyToManyField(through='main.ProjectCostDriver', to='main.costdriver'),
        ),
        migrations.CreateModel(
            name='ProjectScaleDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Nominal'), (4, 'High'), (5, 'Very High'), (6, 'Extra High')])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project')),
                ('scale_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.scaledriver')),
            ],
            options={
                'unique_together': {('project', 'scale_driver')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='scale_drivers',
            field=models.ManyToManyField(through='main.ProjectScaleDriver', to='main.scaledriver'),
        ),
    ]
