# Generated by Django 5.2.1 on 2025-05-22 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_costdriver_project_scaledriver_projectcostdriver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='size_kloc',
            field=models.PositiveIntegerField(help_text='Size in thousands of lines of code (KLOC)', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
