# Generated by Django 5.2.1 on 2025-05-22 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_project_size_kloc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scaledriver',
            name='rating',
        ),
    ]
